### ISSUE TITLE
Stuck at install desktop environment

### ISSUE THREAD

**Issue by wezm** [slayerizer/arch_installer#3]
I've done many manual Arch installs before. Using the script to automate an install in a VM. I kind of guessed from manual install experience what was needed for "custom locale string". I note that the prompt for the change locale option says, "Do you wish to install a Desktop environment?". After that there was an error regarding keyboard layout and now I can't seem to proceed as answering the desktop environment question just shows it again.

```
-[Change locale]---------------------
1: English - United States
2: English - UK
3: English - Canada
4: French  - Canada
5: French  - France
C: Custom
E: exit
Do you wish to install a Desktop environment? [1-5,c,e] : c
Enter the custom locale string : en_AU.UTF-8
------------------------------------------------
-[Change keyboard layout]---------------------
1: United States
2: UK
3: Français - Canada
4: Français - France
Cc: Custom
e: exit
Valid keyboard layouts:
Failed to open keyboard mapping list. No such file or directory

Do you wish to install a Desktop environment? [1,n] : n
Do you wish to install a Desktop environment? [1,n] : n
Do you wish to install a Desktop environment? [1,n] :
Do you wish to install a Desktop environment? [1,n] : n
Do you wish to install a Desktop environment? [1,n] : n
Do you wish to install a Desktop environment? [1,n] : n
Do you wish to install a Desktop environment? [1,n] : n
Do you wish to install a Desktop environment? [1,n] : n
Do you wish to install a Desktop environment? [1,n] : n
Do you wish to install a Desktop environment? [1,n] : n
```

**Comment by wezm** [comment]
Hmm there seem to be several issues with `select-locale` script:

- Prompt here: https://github.com/slayerizer/arch_installer/blob/master/select-locale.sh#L13
- And prompt here: https://github.com/slayerizer/arch_installer/blob/master/select-locale.sh#L38

**Comment by LRA-QC** [comment]
I will inspect! thanks for letting me know, all my current selections worked so far.

**Comment by LRA-QC** [comment]
OK, I fixed the prompt and added extra validation for review, thanks for the issue reporting.
